### ISSUE TITLE
Calculation scheme for time-consuming methods

### ISSUE THREAD

**Issue by jssalonen** [SimonGoring/NoAnalogueError#4]
Need to decide a method to do a representative set of reconstructions with calculation-heavy methods (BRTs and random forest) which we cannot feasibly do all ~~112~~ 23.1 million iterations with.

This is one alternative:

Set up a boolean matrix prepared.recons[i][j], where i is a calibration set sample number 1...2289 and j is one of the used analogue distances 0...100. Fill the matrix initially with FALSE. Then start running the reconstructions in the following loop:

```
while (prepared.recons not full of TRUE) {         # this will never be met
   i <- random integer 1...2289
   j <- random integer 0...100
   if (prepared.recons[i][j] == FALSE) {
      Run reconstructions with 100 bootstrapped calibration sets, using sample i and analogue distance j.
      prepared.recons[i][j] <- TRUE
   }
}
```

This will give us a random selection of observations of how the reconstruction performs with different samples at different analogue distances. 

It will NOT tell us how any given sample performs at all the different analogue distances. If this information is important, then need to think of something else. For example, we could simply take a sample at random, and do the bootstrap runs using a reduced number of analogue distances (e.g. 10). Would need to check if even this is fast enough to be able to test a good selection of different samples (representing different vegetation and pollen composition types).

Alternatively, contact the Centre for Scientific Computing and ask for some time on a Cray, to do the whole thing...

**Comment by SimonGoring** [comment]
Closing, the runs are going fine on AWS servers.
